# Generated by Django 2.1.4 on 2018-12-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('med_worker', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата открытия заявки')),
                ('closing_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата закрытия заявки')),
                ('med_worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='med_worker.MedWorkerProfile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.PatientProfile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='Наименование статуса')),
                ('is_application_done', models.BooleanField(default=False, verbose_name='Заявка закрыта')),
            ],
        ),
        migrations.AddField(
            model_name='applicationarchive',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.ApplicationStatus'),
        ),
    ]
