# Generated by Django 2.1.4 on 2018-12-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('med_worker', '0001_initial'),
        ('service', '0002_auto_20181216_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='med_worker.MedWorker')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.Patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='Статус заявки')),
            ],
        ),
        migrations.AddField(
            model_name='applicationarchive',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.ApplicationStatus'),
        ),
    ]
