# Generated by Django 2.1.4 on 2018-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='is_application_done',
            field=models.BooleanField(default=False, verbose_name='Заявка выполнена'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Наименование статуса'),
        ),
    ]
