# Generated by Django 2.1.4 on 2018-12-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2, verbose_name='Номер палаты')),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ward',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='service.Ward', verbose_name='Номер палаты'),
            preserve_default=False,
        ),
    ]
