# Generated by Django 2.1.4 on 2018-12-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearchive',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='servicearchive',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='done',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Наименование услуги'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type',
            field=models.CharField(max_length=120, verbose_name='Тип услуги'),
        ),
        migrations.DeleteModel(
            name='ServiceArchive',
        ),
    ]
