# Generated by Django 2.1.4 on 2018-12-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservice',
            name='type',
            field=models.CharField(max_length=120, verbose_name='Наименование типа услуги'),
        ),
    ]
