# Generated by Django 2.1.4 on 2018-12-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20181227_1801'),
        ('service', '0004_auto_20181224_2142'),
    ]

    operations = [
    ]
