# Generated by Django 2.1.4 on 2018-12-17 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medworkerprofile',
            old_name='surname',
            new_name='mid_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='surname',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='mid_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
    ]
